(define (equal? a b)
    (cond ((and (pair? a) (pair? b))
                (and (eq? (car a) (car b))
                     (equal? (cdr a) (cdr b))))
          ((pair? a) False)
          ((pair? b) False)
          (else (eq? a b))))

; test
(newline)
(display (equal? 'a 'b))
(newline)
(display (equal? 'a 'a))
(newline)
(display (equal? '(a b) '(a b)))
(newline)
(display (equal? '(a b) '(a c)))
(newline)
(display (equal? '(a b) 'a))
(newline)
(display (equal? 'a '(a b)))
(newline)
(display (equal? '(a b) '((a) (b))))
